FROM fedora:latest

RUN dnf install -y file graphviz python3-pip python3-devel gcc diffutils ncurses fish tmux python3-scikit-learn python3-numpy ranger vim-X11
RUN pip3 install python-Levenshtein mypy black py2cfg scikit-learn numpy
# RUN useradd -m student
# USER student
# WORKDIR /home/student
