FROM fedora:latest

RUN dnf install -y file graphviz python3-pip python3-devel gcc diffutils ncurses fish tmux python3-numpy python3-pandas ranger vim-X11 git
RUN pip3 install python-Levenshtein mypy black py2cfg numpy pandas
# RUN useradd -m student
# USER student
# WORKDIR /home/student
